
DROP TABLE IF EXISTS shared_file;
DROP TABLE IF EXISTS account;
CREATE TABLE account (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(255),
    role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
    token VARCHAR(255) DEFAULT NULL,
    profile_picture VARCHAR(255) DEFAULT NULL
);
CREATE TABLE shared_file (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    owner VARCHAR(255) NOT NULL,
    filename VARCHAR(255) NOT NULL,
    shared_with VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);